# specify python as the language
language: python

# python versions to be used for testing
python:
  - "2.6"
  - "2.7"

# install jython
before_install:
  - export JYTHON_URL='http://central.maven.org/maven2/org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
  - wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython/bin:$PATH;jython --version

# Before run the test case, we need to make jython run some code
before_script:
  - jython -c "print ''"
  - mvn package
  - export CLASSPATH=lib/*

# test script
script:
    - jython print_args.py a b c 1 2 3
    - jython call_owltools.py
