# specify python as the language
language: python

# python versions to be used for testing
python:
  - "2.6"
  - "2.7"

env:
  - JYTHON=true
  - JYTHON=false

matrix:
  exclude:
    - python: 2.6
      env: JYTHON=true

# we need jython if JYTHON=true
before_install:
  - export JYTHON_URL='http://central.maven.org/maven2/org/python/jython-installer/2.7.0/jython-installer-2.7.0.jar'
  - if [ "$JYTHON" == "true" ]; then wget $JYTHON_URL -O jython_installer.jar; java -jar jython_installer.jar -s -d $HOME/jython; export PATH=$HOME/jython/bin:$PATH;jython --version; fi

# Before run the test case, we need to make jython run some code
before_script:
  - if [ "$JYTHON" == "true" ]; then export PYTHON_EXE=jython; jython -c "print ''"; else export PYTHON_EXE=python; fi
  - mvn package
  - CLASSPATH=$CLASSPATH:$(for i in lib/*.jar ; do echo -n $i: ; done).
  - export

# test script
script:
    - $PYTHON_EXE print_args.py a b c 1 2 3
    - $PYTHON_EXE call_owltools.py
